name: Build Windows Exe

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build HorionInjector.sln --configuration Release --no-restore

      - name: Publish Windows executable
        run: |
          dotnet publish HorionInjector.sln \
            --configuration Release \
            --runtime win-x64 \
            --self-contained true \
            --output ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: publish/
          retention-days: 30        # optional: customize retention
          compression-level: 5     # optional: adjust speed vs size
